export const FETCH_STUDENT_REQUEST = "FETCH_STUDENT_REQUEST"
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS"
export const FETCH_STUDENT_FAILURE = "FETCH_STUDENT_FAILURE"

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE"