export const FETCH_COURSE_REQUEST = "FETCH_COURSE_REQUEST"
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS"
export const FETCH_COURSE_FAILURE = "FETCH_COURSE_FAILURE"

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST"
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS"
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE"