export const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST"
export const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS"
export const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE"

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST"
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE"